version: '3.8'

services:
  elt-app:
    image: elt-pipeline:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=elt_db
      - DB_USER=postgres
      - DB_PASS=postgres
    volumes:
      - .:/app
    command: ["python", "main.py"]

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: elt_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: